# Generated by Django 5.2.1 on 2025-05-17 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_review_comment_remove_review_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default='No content', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product'),
            preserve_default=False,
        ),
    ]
