# Generated by Django 5.2.1 on 2025-05-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealsandoffers', '0001_initial'),
        ('store', '0016_orderstatusupdate_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='products',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
    ]
