# Generated by Django 5.2.1 on 2025-05-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealsandoffers', '0002_deal_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deals_images/'),
        ),
    ]
