# Generated by Django 5.2.1 on 2025-06-11 10:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealsandoffers', '0003_deal_image'),
        ('store', '0017_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='products',
        ),
        migrations.AddField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deals/'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
